### ISSUE TITLE
Копипасти с умуом

### ISSUE THREAD

**Issue by Red-Cat-Fat** [votizlov/Unity_1#10]
Я про класс ExplosionForce. Не стоит бездумно копировать откуда-то и вставлять в проект
https://github.com/votizlov/Unity_1/blob/9efb81df35e2c8503ee6f40f768030011133b407/Clicker/Assets/Scripts/Objects/ExplosionForce.cs#L6

**Comment by votizlov** [comment]
Этот класс шел вместе с библиотекой для разламывания, даже не особо проверял его, а что с ним не так?

**Comment by Red-Cat-Fat** [comment]
То, что нужно смотреть и понимать что ты копируешь. Поддерживать кодстайл и т.п. Нельзя просто взять, скопировать-вставить и так оставить.

**Comment by votizlov** [comment]
А, понял, осознал. Почему-то даже не задумался об этом.
