### ISSUE TITLE
Нейминг 

### ISSUE THREAD

**Issue by Red-Cat-Fat** [votizlov/Unity_1#2]
https://github.com/votizlov/Unity_1/blob/428957fbb2895133d82ef0086bb833e2f874df21/Clicker/Assets/Scripts/DestroyAction.cs#L8-L10
### Отступы
Только TAB. Пробелам смерть!
### Имена

- Переменные внутри функции - с маленькой буквы camelCase (int someVar = 0;)
- Поле класса private/internal - с подчеркивания, _camelCase (private int _someVar;)
- Поле класса protected/public - с большой буквы, CamelCase (public int SomeVar;)
- Имена файлов, классов и неймспейсов - с большой буквы, CamelCase (EditorUtils.GUIWindow)
- Для свойств и событий - аналогично полям.
- Имя события не должно содержать On, должно заканчиваться на Event (public event System.Action ItemClickEvent;)
- Имя метода, отлавливающего событие должно содержать On, иметь совершённую форму и не должно заканчиваться на Event (private void OnItemClicked())
- Все имена функций - с большой буквы, CamelCase (private void SomeFunc())

### Общее

- Все поля, функции, свойства и события должны быть с явным модификатором (private/public/protected/internal)
- Для всех классов должен быть указан неймспейс
- Неймспейс определяется путем к скрипту, например скрипт в Assets/Scripts/Game/UI должен иметь неймспейс Game.UI, а скрипт в Assets/Scripts/Common/UI - неймспейс Common.UI
- Нельзя создавать неймспейс с именем используемых класса (Editor.Utils)
- {} скобки - на новой строке
- Не стоит пренебрегать {} для однострочных циклов и условий - меньше багов будет и проще потом править
- Unity создает по дефолту файлы с функциями Start и Update - обязательно удаляйте их если не используете

**Comment by votizlov** [comment]
Игнор файл теперь выглядит так:  https://github.com/votizlov/Unity_1/blob/master/.gitignore (изменения неудобно смотреть потому что надо было удалять существующие файлы и изза невнимательности получилось несколько коммитов)

**Comment by votizlov** [comment]
Здесь пофикшены неймспейсы и названия(и я забыл удалить .idea):
https://github.com/votizlov/Unity_1/commit/85553af9e25ae2ddcefb48bd7c04b32be0fce9d8

**Comment by Red-Cat-Fat** [comment]
А ишью зачем позакрывал сам?!
